services:
  database:
    image: postgres:stable
    container_name: sharex_db
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: sharex
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./sharex_db:/var/lib/postgresql/data/pgdata:rw"
    healthcheck:
      # pgsql restarts a few times at the first run so we wait a bit.
      test: ["CMD-SHELL", "sleep 3; pg_isready -U admin -d sharex"]
      interval: 1s
      timeout: 10s
      retries: 30

  sharex_server:
    image: 0x25cbfc4f/sharex_server:latest
    container_name: sharex_server
    restart: always
    ports:
      - 80:5000
    environment:
      # URL for your server, you can bind it to any interface or port
      ASPNETCORE_URLS: http://0.0.0.0:5000
      # Server environment. You can leave it with 'Production'
      ASPNETCORE_ENVIRONMENT: Production
    volumes:
      - "./media:/app/media:rw"
      - "./appsettings.Production.json:/app/appsettings.Production.json:ro"
    depends_on:
      database:
        condition: service_healthy
